<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use Illuminate\Support\Facades\Hash;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $images1 = [
            'property/ex1.jpg',
            'property/ex2.jpg',
            'property/ex3.jpg',
            // Add more image paths as needed
        ];

        $images2 = [
            'property/image1.jpg',
            'property/image2.jpg',
            'property/image3.jpg',
            // Add more image paths as needed
        ];

        $images3 = [
            'property/img1.jpg',
            'property/img2.jpg',
            'property/img3.jpg',
            // Add more image paths as needed
        ];

        $images4 = [
            'property/photo1.jpg',
            'property/photo2.jpg',
            'property/photo3.jpg',
            // Add more image paths as needed
        ];

        $images5 = [
            'property/sample1.jpg',
            'property/sample2.jpg',
            'property/sample3.jpg',
            // Add more image paths as needed
        ];

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Home Office 1',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Studio Home Office',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '22.40 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO1.png',
            'img'=> json_encode($images1),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Home Office 2',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Studio Home Office',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '37.20 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO2.png',
            'img'=> json_encode($images2),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Home Office 3',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Studio Home Office',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '51 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO3.png',
            'img'=> json_encode($images3),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: 1-Bedroom Home Office 1',
            'description' => 'Discover the perfect blend of comfort, convenience, and modern living in the heart of Cebu City. Welcome to Vertex Central, where the future of urban living begins. This spacious 1-bedroom home office unit is a dream come true for professionals and young families looking for a space that offers both a cozy living environment and the functionality of a home office.',
            'unitdesc' => 'With 42.55 square meters of living space, you will have room to stretch out and make this unit truly your own.',
            'beddesc' => 'Work from the comfort of your home in your dedicated office space, designed to enhance productivity. This features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 5,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Bedroom Home Office',
            'type' => 'Condominium',
            'price' =>'5,000,000',
            'sizes' => '42.55 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BOHO1.png',
            'img'=> json_encode($images4),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: 1-Bedroom Home Office 2',
            'description' => 'Discover the perfect blend of comfort, convenience, and modern living in the heart of Cebu City. Welcome to Vertex Central, where the future of urban living begins. This spacious 1-bedroom home office unit is a dream come true for professionals and young families looking for a space that offers both a cozy living environment and the functionality of a home office.',
            'unitdesc' => 'With 42.55 square meters of living space, you will have room to stretch out and make this unit truly your own.',
            'beddesc' => 'Work from the comfort of your home in your dedicated office space, designed to enhance productivity. This features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 5,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Bedroom Home Office',
            'type' => 'Condominium',
            'price' =>'5,000,000',
            'sizes' => '49 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Featured',
            'coverphoto' => 'images/VertexCentral/V-BOHO2.png',
            'img'=> json_encode($images2),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: 1-Bedroom Home Office 3',
            'description' => 'Discover the perfect blend of comfort, convenience, and modern living in the heart of Cebu City. Welcome to Vertex Central, where the future of urban living begins. This spacious 1-bedroom home office unit is a dream come true for professionals and young families looking for a space that offers both a cozy living environment and the functionality of a home office.',
            'unitdesc' => 'With 42.55 square meters of living space, you will have room to stretch out and make this unit truly your own.',
            'beddesc' => 'Work from the comfort of your home in your dedicated office space, designed to enhance productivity. This features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 5,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Bedroom Home Office',
            'type' => 'Condominium',
            'price' =>'5,000,000',
            'sizes' => '71.60 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BOHO3.png',
            'img'=> json_encode($images3),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: 1-bedroom Home Office 4',
            'description' => 'Discover the perfect blend of comfort, convenience, and modern living in the heart of Cebu City. Welcome to Vertex Central, where the future of urban living begins. This spacious 1-bedroom home office unit is a dream come true for professionals and young families looking for a space that offers both a cozy living environment and the functionality of a home office.',
            'unitdesc' => 'With 42.55 square meters of living space, you will have room to stretch out and make this unit truly your own.',
            'beddesc' => 'Work from the comfort of your home in your dedicated office space, designed to enhance productivity. This features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 5,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Bedroom Home Office',
            'type' => 'Condominium',
            'price' =>'5,000,000',
            'sizes' => '73 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BOHO4.png',
            'img'=> json_encode($images4),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: 1-Bedroom Home Office 5',
            'description' => 'Discover the perfect blend of comfort, convenience, and modern living in the heart of Cebu City. Welcome to Vertex Central, where the future of urban living begins. This spacious 1-bedroom home office unit is a dream come true for professionals and young families looking for a space that offers both a cozy living environment and the functionality of a home office.',
            'unitdesc' => 'With 42.55 square meters of living space, you will have room to stretch out and make this unit truly your own.',
            'beddesc' => 'Work from the comfort of your home in your dedicated office space, designed to enhance productivity. This features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 5,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Bedroom Home Office',
            'type' => 'Condominium',
            'price' =>'5,000,000',
            'sizes' => '73 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BOHO5.png',
            'img'=> json_encode($images5),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Special Unit Home Office 1 ',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Special Unit',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '30.20 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO1.png',
            'img'=> json_encode($images5),
            'vid'=> NULL,
        ]);

        
        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Special Unit Home Office 2',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Special Unit',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '30.20 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO2.png',
            'img'=> json_encode($images4),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Special Unit Home Office 3',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Special Unit',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '24 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO3.png',
            'img'=> json_encode($images2),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Special Unit Home Office 4',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Special Unit',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '26.05 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO4.png',
            'img'=> json_encode($images1),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Special Unit Home Office 5',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Special Unit',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '38.10 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO5.png',
            'img'=> json_encode($images2),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Special Unit Home Office 6',
            'description' => 'A modern and versatile Studio Home Office condominium in the heart of Cebu City. This pre-selling gem is the perfect canvas for professionals, entrepreneurs, or investors looking to create a dynamic urban living and working space. Invest in your future with this pre-selling property, offering you an affordable entry into the Cebu City real estate market.',
            'unitdesc' => 'With 22.40 square meters of space, Vertex Central offers a spacious studio layout that combines the comfort of a living space with the flexibility of a home office, making it ideal for professionals who value work-life balance.',
            'beddesc' => 'The apartment features one bedroom, providing a private and comfortable space for rest and relaxation.',
            'furnishdesc' => 'The unit comes unfurnished, allowing you the freedom to design and customize your space to meet your unique needs and preferences',
            'pricedesc' => 'Priced at just PHP 3,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living and working space.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Special Unit',
            'type' => 'Condominium',
            'price' =>'3,000,000',
            'sizes' => '34 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO6.png',
            'img'=> json_encode($images1),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Residence 1',
            'description' => 'Welcome to the future of urban living at Vertex Central. This modern Studio Residence is designed to offer a comfortable and convenient lifestyle for both professionals and individuals seeking the perfect urban retreat.',
            'unitdesc' => 'This well-designed 22.40 square meter studio residence maximizes space utilization, creating a cozy and functional living environment.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'As a "Not Furnished" unit, you have the creative freedom to design and furnish the interior to your own preferences, allowing you to create a space that truly reflects your style and personality.',
            'pricedesc' => 'Priced at just PHP 4,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Studio Residence',
            'type' => 'Condominium',
            'price' =>'4,000,000',
            'sizes' => '22.40 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-STUDIO.png',
            'img'=> json_encode($images4),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Residence 2',
            'description' => 'Welcome to the future of urban living at Vertex Central. This modern Studio Residence is designed to offer a comfortable and convenient lifestyle for both professionals and individuals seeking the perfect urban retreat.',
            'unitdesc' => 'This well-designed 22.40 square meter studio residence maximizes space utilization, creating a cozy and functional living environment.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'As a "Not Furnished" unit, you have the creative freedom to design and furnish the interior to your own preferences, allowing you to create a space that truly reflects your style and personality.',
            'pricedesc' => 'Priced at just PHP 4,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Studio Residence',
            'type' => 'Condominium',
            'price' =>'4,000,000',
            'sizes' => '27.45 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-STUDIO2.png',
            'img'=> json_encode($images5),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Residence 3',
            'description' => 'Welcome to the future of urban living at Vertex Central. This modern Studio Residence is designed to offer a comfortable and convenient lifestyle for both professionals and individuals seeking the perfect urban retreat.',
            'unitdesc' => 'This well-designed 22.40 square meter studio residence maximizes space utilization, creating a cozy and functional living environment.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'As a "Not Furnished" unit, you have the creative freedom to design and furnish the interior to your own preferences, allowing you to create a space that truly reflects your style and personality.',
            'pricedesc' => 'Priced at just PHP 4,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Studio Residence',
            'type' => 'Condominium',
            'price' =>'4,000,000',
            'sizes' => '34.55 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-STUDIO3.png',
            'img'=> json_encode($images1),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Residence 4',
            'description' => 'Welcome to the future of urban living at Vertex Central. This modern Studio Residence is designed to offer a comfortable and convenient lifestyle for both professionals and individuals seeking the perfect urban retreat.',
            'unitdesc' => 'This well-designed 22.40 square meter studio residence maximizes space utilization, creating a cozy and functional living environment.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'As a "Not Furnished" unit, you have the creative freedom to design and furnish the interior to your own preferences, allowing you to create a space that truly reflects your style and personality.',
            'pricedesc' => 'Priced at just PHP 4,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Studio Residence',
            'type' => 'Condominium',
            'price' =>'4,000,000',
            'sizes' => '29.30 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-STUDIO4.png',
            'img'=> json_encode($images2),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: Studio Residence 5',
            'description' => 'Welcome to the future of urban living at Vertex Central. This modern Studio Residence is designed to offer a comfortable and convenient lifestyle for both professionals and individuals seeking the perfect urban retreat.',
            'unitdesc' => 'This well-designed 22.40 square meter studio residence maximizes space utilization, creating a cozy and functional living environment.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'As a "Not Furnished" unit, you have the creative freedom to design and furnish the interior to your own preferences, allowing you to create a space that truly reflects your style and personality.',
            'pricedesc' => 'Priced at just PHP 4,000,000, Vertex Central offers an excellent value proposition, making it an attractive opportunity for those seeking an affordable yet stylish urban living.',
            'locationdesc' => 'Situated on Archbishop Reyes Avenue, you will enjoy easy access to business centers, shopping districts, dining options, and public transportation, making daily life both convenient and enjoyable.',
            'unitType' => 'Studio Residence',
            'type' => 'Condominium',
            'price' =>'4,000,000',
            'sizes' => '22.40 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-STUDIO5.png',
            'img'=> json_encode($images3),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: 1-Bedroom Residence 1',
            'description' => 'Vertex Central welcomes you to an exceptional living experience in the heart of Cebu City. This 1-Bedroom Residence is a promising investment opportunity in Cebu Citys thriving real estate market. With its pre-selling status, it presents an attractive option to secure a valuable property at a competitive price.',
            'unitdesc' => 'With a generous 42.55 square meters of living space, this 1-bedroom residence provides ample room for your comfort and creative use. The thoughtfully designed layout ensures the best use of space, with a comfortable bedroom and living area.',
            'beddesc' => ' This 1-Bedroom Residence at Vertex Central offers a perfect blend of contemporary living and functional design. The spacious bedroom ensures comfort and privacy, making it an ideal choice for singles, couples, or young professionals.',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a price of PHP 9,000,000, Vertex Central offers excellent value for a one bedroom unit in Cebu City',
            'locationdesc' => 'Situated on a prime location, Vertex Central places you at the center of Cebu City vibrant scene, with shopping, dining, and entertainment options at your doorstep.',
            'unitType' => '1 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'9,000,000',
            'sizes' => '42.55 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BR1.png',
            'img'=> json_encode($images4),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Central: 1-Bedroom Residence 2',
            'description' => 'Vertex Central welcomes you to an exceptional living experience in the heart of Cebu City. This 1-Bedroom Residence is a promising investment opportunity in Cebu Citys thriving real estate market. With its pre-selling status, it presents an attractive option to secure a valuable property at a competitive price.',
            'unitdesc' => 'With a generous 42.55 square meters of living space, this 1-bedroom residence provides ample room for your comfort and creative use. The thoughtfully designed layout ensures the best use of space, with a comfortable bedroom and living area.',
            'beddesc' => ' This 1-Bedroom Residence at Vertex Central offers a perfect blend of contemporary living and functional design. The spacious bedroom ensures comfort and privacy, making it an ideal choice for singles, couples, or young professionals.',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a price of PHP 9,000,000, Vertex Central offers excellent value for a one bedroom unit in Cebu City',
            'locationdesc' => 'Situated on a prime location, Vertex Central places you at the center of Cebu City vibrant scene, with shopping, dining, and entertainment options at your doorstep.',
            'unitType' => '1 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'9,000,000',
            'sizes' => '51.70 Sqm',
            'address'=> ' Archbishop Reyes Ave',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BR2.png',
            'img'=> json_encode($images5),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Coast: Studio Unit',
            'description' => 'Welcome to Vertex Coast, where seaside living meets modern comfort. This Studio Unit offers a unique opportunity to embrace coastal living in the heart of Lapu-Lapu City, Cebu. This Studio Unit at Vertex Coast represents an enticing investment opportunity in Lapu-Lapu Citys growing real estate market. With the competitive pre-selling price, it is an ideal time to invest in seaside living.',
            'unitdesc' => 'This well-designed 26.15 square meter studio unit maximizes space utilization, creating a cozy living environment.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'As a "Not Furnished" unit, you have the creative freedom to design and furnish the interior according to your preferences, allowing you to create a space that truly reflects your style and personality.',
            'pricedesc' => 'At a price of PHP 4,544,402.00, It is an excellent value for a studio unit in Lapu-Lapu City',
            'locationdesc' => 'With a picturesque location along Punta Engano Rd, Vertex Coast allows you to savor the serenity of coastal living with easy access to the beach.',
            'unitType' => 'Studio Residence',
            'type' => 'Condominium',
            'price' =>'4,544,402.00',
            'sizes' => '26.15 Sqm',
            'address'=> 'Brgy, Punta Engano Rd',
            'state'=> 'Lapu-Lapu City',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-STUDIO.png',
            'img'=> json_encode($images1),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Coast: Studio Home Office',
            'description' => 'Discover the perfect blend of coastal living and modern workspace at Vertex Coast. This Studio Home Office offers an opportunity to create a productive work environment while enjoying the serenity of Lapu-Lapu Citys coastal lifestyle.',
            'unitdesc' => 'Enjoy the unique combination of work and relaxation in this 26.15 square meter studio home office, where you can be productive and unwind by the coast.',
            'beddesc' => 'This is a studio home office so there are no bedrooms',
            'furnishdesc' => 'As a "Not Furnished" unit, you have the creative freedom to design and furnish the interior according to your preferences, allowing you to create a space that truly reflects your style and personality.',
            'pricedesc' => 'At a price of PHP 4,544,402.00, It is an excellent value for a studio unit in Lapu-Lapu City',
            'locationdesc' => 'With a picturesque location along Punta Engano Rd, Vertex Coast allows you to savor the serenity of coastal living with easy access to the beach.',
            'unitType' => 'Studio Home Office',
            'type' => 'Condominium',
            'price' =>'4,774,469',
            'sizes' => '26.15 Sqm',
            'address'=> 'Brgy, Punta Engano Rd',
            'state'=> 'Lapu-Lapu City',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-SOHO1.png',
            'img'=> json_encode($images2),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Coast: 1-Bedroom Residence',
            'description' => 'Embrace the coastal lifestyle and modern living in one with this 1-Bedroom Residence at Vertex Coast. Located in the heart of Lapu-Lapu City, this spacious unit offers both comfort and a serene seaside experience.',
            'unitdesc' => 'With 42.55 square meters of living space, there is ample room for relaxation and creativity.',
            'beddesc' => 'This 1-Bedroom Residence combines modern comfort with coastal serenity, providing an ideal living space for singles, couples, or professionals.',
            'furnishdesc' => 'This unit comes unfurnished, providing you with the creative freedom to design and furnish the interior to match your unique style and preferences, ensuring your new space reflects your personality.',
            'pricedesc' => 'At a price of PHP 9,316,151.80, It is an excellent value for a 1-Bedroom Residence in Lapu-Lapu City',
            'locationdesc' => 'With a picturesque location along Punta Engano Rd, Vertex Coast allows you to savor the serenity of coastal living with easy access to the beach.',
            'unitType' => '1 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'9,316,151.80',
            'sizes' => '42.55 Sqm',
            'address'=> 'Brgy, Punta Engano Rd',
            'state'=> 'Lapu-Lapu City',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BR1.png',   
            'img'=> json_encode($images3),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Coast: 2-Bedroom Residence',
            'description' => 'Experience the best of coastal living with modern comfort in this 2-Bedroom Residence at Vertex Coast. Nestled in Lapu-Lapu City, this spacious unit offers the perfect balance of space and seaside serenity.',
            'unitdesc' => 'With 57.30 square meters of living space, there is room to create the ideal setting for your coastal home.',
            'beddesc' => 'This 2-Bedroom Residence at Vertex Coast presents a compelling investment opportunity in Lapu-Lapu Citys growing real estate market. With the pre-selling pricing, it is an ideal time to invest in a spacious seaside living space.',
            'furnishdesc' => 'This unit comes unfurnished, offering you the creative freedom to design and furnish the interior to match your unique style and preferences, ensuring your new space reflects your personality.',
            'pricedesc' => 'At a price of PHP 10,351,279, It is an excellent value for a 2-Bedroom Residence in Lapu-Lapu City',
            'locationdesc' => 'With a picturesque location along Punta Engano Rd, Vertex Coast allows you to savor the serenity of coastal living with easy access to the beach.',
            'type' => 'Condominium',
            'unitType' => '2 Bedroom Residence',
            'price' =>'10,351,279',
            'sizes' => '57.30 Sqm',
            'address'=> 'Brgy, Punta Engano Rd',
            'state'=> 'Lapu-Lapu City',
            'zip'=> '6666',
            'bed'=> '2',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BR2.png',
            'img'=> json_encode($images4),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Vertex Coast: 1-Bedroom Studio Home Office',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => 'Studio Home Office',
            'type' => 'Condominium',
            'price' =>'11,615,168',
            'sizes' => '57.30 Sqm',
            'address'=> 'Brgy, Punta Engano Rd',
            'state'=> 'Lapu-Lapu City',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/VertexCentral/V-BOHO4.png',
            'img'=> json_encode($images5),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: Studio Unit',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => 'Studio Residence',
            'type' => 'Condominium',
            'price' =>'6,000,000',
            'sizes' => '43.85 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/TEG_STUDIO.png',
            'img'=> json_encode($images1),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: Studio Unit With Balcony',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => 'Studio Residence',
            'type' => 'Condominium',
            'price' =>'9,000,000',
            'sizes' => '43.85 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '0',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/TEG_STUDIO.png',
            'img'=> json_encode($images2),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 1 Bedroom Unit',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'type' => '1 Bedroom Residence',
            'unitType' => 'Condominium',
            'price' =>'9,200,000',
            'sizes' => '47.59 - 77.82 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/TEG_1BR.png',
            'img'=> json_encode($images3),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 1 Bedroom Unit With Balcony',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => '1 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'9,300,000',
            'sizes' => '47.59 - 77.82 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/TEG_1BR.png',
            'img'=> json_encode($images4),
            'vid'=> NULL,
        ]);


        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 1 Bedroom Unit With Garden',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => '1 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'9,300,000',
            'sizes' => '47.59 - 77.82 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '1',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/1BR-Garden-unit.png',
            'img'=> json_encode($images5),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 2 Bedroom Unit A',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => '2 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'16,700,000',
            'sizes' => '73-84 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '2',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/TEG_2BRa.png',
            'img'=> json_encode($images1),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 2 Bedroom Unit B',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => '2 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'16,700,000',
            'sizes' => '73-84 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '2',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/TEG_2BRb.png',
            'img'=> json_encode($images2),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 2 Bedroom Unit C',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => '2 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'16,700,000',
            'sizes' => '73-84 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '2',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/TEG_2BRc.png',
            'img'=> json_encode($images3),
            'vid'=> NULL,
        ]);
       
        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 2 Bedroom Edge Unit Left Corner',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => '2 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'16,700,000',
            'sizes' => '73.35 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '2',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/2BR-Edge-LeftUnit.png',
            'img'=> json_encode($images4),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 2 Bedroom Edge Unit Right Corner',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => '2 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'16,700,000',
            'sizes' => '73.35 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '2',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/2BR-Edge-RightUnit.png',
            'img'=> json_encode($images5),
            'vid'=> NULL,
        ]);

        Property::create([
            'availability' => 'Pre-Selling',
            'furnish' => 'Not Furnished',
            'name' => 'Taft East Gate: 2 Bedroom with Garden',
            'description' => 'A spacious studio unit located in the desirable neighborhood of Banawa, Cebu. This unfurnished studio offers a blank canvas for you to create your ideal living space. Its now available for rent, providing a flexible and affordable housing option in one of Cebus most sought-after areas.',
            'unitdesc' => 'With 18 square meters of space, Minded Manor offers plenty of room to live and entertain comfortably.',
            'beddesc' => 'This is a studio unit so there are no bedrooms',
            'furnishdesc' => 'The studio is not furnished, giving you the freedom to personalize the space to your taste and needs.',
            'pricedesc' => 'At a rental price of PHP 2,000,000, The Views offers excellent value for a studio unit in Banawa, Cebu.',
            'locationdesc' => 'Situated in Banawa, youll have easy access to shopping centers, dining options, schools, and transportation hubs, ensuring a convenient and enjoyable lifestyle.',
            'unitType' => '2 Bedroom Residence',
            'type' => 'Condominium',
            'price' =>'22,900,000',
            'sizes' => '84 Sqm',
            'address'=> 'Pope John Paul II Avenue cor. Cardinal Rosales Avenue',
            'state'=> 'Cebu City, Cebu',
            'zip'=> '6666',
            'bed'=> '2',
            'status' => 'Approved',
            'featured'=> 'Not Featured',
            'coverphoto' => 'images/TaftEastGate/2BR-Garden-Unit.png',
            'img'=> json_encode($images1),
            'vid'=> NULL,
        ]);
       
       

    }
}
